apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: vm-daily
  namespace: openshift-adp
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
      - oadp-lab
    snapshotMoveData: true
    ttl: 168h0m0s
